export const COUNTRIES: any[] = [
    { value: "Afghanistan", abbrev: "AF", label: "Afghanistan" },
    { value: "Åland Islands", abbrev: "AX", label: "Åland Islands" },
    { value: "Albania", abbrev: "AL", label: "Albania" },
    { value: "Algeria", abbrev: "DZ", label: "Algeria" },
    { value: "American Samoa", abbrev: "AS", label: "American Samoa" },
    { value: "Andorra", abbrev: "AD", label: "Andorra" },
    { value: "Angola", abbrev: "AO", label: "Angola" },
    { value: "Anguilla", abbrev: "AI", label: "Anguilla" },
    { value: "Antarctica", abbrev: "AQ", label: "Antarctica" },
    { value: "Antigua and Barbuda", abbrev: "AG", label: "Antigua and Barbuda" },
    { value: "Argentina", abbrev: "AR", label: "Argentina" },
    { value: "Armenia", abbrev: "AM", label: "Armenia" },
    { value: "Aruba", abbrev: "AW", label: "Aruba" },
    { value: "Australia", abbrev: "AU", label: "Australia" },
    { value: "Austria", abbrev: "AT", label: "Austria" },
    { value: "Azerbaijan", abbrev: "AZ", label: "Azerbaijan" },
    { value: "Bahamas", abbrev: "BS", label: "Bahamas" },
    { value: "Bahrain", abbrev: "BH", label: "Bahrain" },
    { value: "Bangladesh", abbrev: "BD", label: "Bangladesh" },
    { value: "Barbados", abbrev: "BB", label: "Barbados" },
    { value: "Belarus", abbrev: "BY", label: "Belarus" },
    { value: "Belgium", abbrev: "BE", label: "Belgium" },
    { value: "Belize", abbrev: "BZ", label: "Belize" },
    { value: "Benin", abbrev: "BJ", label: "Benin" },
    { value: "Bermuda", abbrev: "BM", label: "Bermuda" },
    { value: "Bhutan", abbrev: "BT", label: "Bhutan" },
    { value: "Bolivia", abbrev: "BO", label: "Bolivia" },
    { value: "Bosnia and Herzegovina", abbrev: "BA", label: "Bosnia and Herzegovina" },
    { value: "Botswana", abbrev: "BW", label: "Botswana" },
    { value: "Bouvet Island", abbrev: "BV", label: "Bouvet Island" },
    { value: "Brazil", abbrev: "BR", label: "Brazil" },
    { value: "British Indian Ocean Territory", abbrev: "IO", label: "British Indian Ocean Territory" },
    { value: "Brunei Darussalam", abbrev: "BN", label: "Brunei Darussalam" },
    { value: "Bulgaria", abbrev: "BG", label: "Bulgaria" },
    { value: "Burkina Faso", abbrev: "BF", label: "Burkina Faso" },
    { value: "Burundi", abbrev: "BI", label: "Burundi" },
    { value: "Cambodia", abbrev: "KH", label: "Cambodia" },
    { value: "Cameroon", abbrev: "CM", label: "Cameroon" },
    { value: "Canada", abbrev: "CA", label: "Canada" },
    { value: "Cape Verde", abbrev: "CV", label: "Cape Verde" },
    { value: "Cayman Islands", abbrev: "KY", label: "Cayman Islands" },
    { value: "Central African Republic", abbrev: "CF", label: "Central African Republic" },
    { value: "Chad", abbrev: "TD", label: "Chad" },
    { value: "Chile", abbrev: "CL", label: "Chile" },
    { value: "China", abbrev: "CN", label: "China" },
    { value: "Christmas Island", abbrev: "CX", label: "Christmas Island" },
    { value: "Cocos (Keeling) Islands", abbrev: "CC", label: "Cocos (Keeling) Islands" },
    { value: "Colombia", abbrev: "CO", label: "Colombia" },
    { value: "Comoros", abbrev: "KM", label: "Comoros" },
    { value: "Congo", abbrev: "CG", label: "Congo" },
    { value: "Congo, The Democratic Republic of the", abbrev: "CD", label: "Congo, The Democratic Republic of the" },
    { value: "Cook Islands", abbrev: "CK", label: "Cook Islands" },
    { value: "Costa Rica", abbrev: "CR", label: "Costa Rica" },
    { value: "Cote D'Ivoire", abbrev: "CI", label: "Cote D'Ivoire" },
    { value: "Croatia", abbrev: "HR", label: "Croatia" },
    { value: "Cuba", abbrev: "CU", label: "Cuba" },
    { value: "Cyprus", abbrev: "CY", label: "Cyprus" },
    { value: "Czech Republic", abbrev: "CZ", label: "Czech Republic" },
    { value: "Denmark", abbrev: "DK", label: "Denmark" },
    { value: "Djibouti", abbrev: "DJ", label: "Djibouti" },
    { value: "Dominica", abbrev: "DM", label: "Dominica" },
    { value: "Dominican Republic", abbrev: "DO", label: "Dominican Republic" },
    { value: "Ecuador", abbrev: "EC", label: "Ecuador" },
    { value: "Egypt", abbrev: "EG", label: "Egypt" },
    { value: "El Salvador", abbrev: "SV", label: "El Salvador" },
    { value: "Equatorial Guinea", abbrev: "GQ", label: "Equatorial Guinea" },
    { value: "Eritrea", abbrev: "ER", label: "Eritrea" },
    { value: "Estonia", abbrev: "EE", label: "Estonia" },
    { value: "Ethiopia", abbrev: "ET", label: "Ethiopia" },
    { value: "Falkland Islands (Malvinas)", abbrev: "FK", label: "Falkland Islands (Malvinas)" },
    { value: "Faroe Islands", abbrev: "FO", label: "Faroe Islands" },
    { value: "Fiji", abbrev: "FJ", label: "Fiji" },
    { value: "Finland", abbrev: "FI", label: "Finland" },
    { value: "France", abbrev: "FR", label: "France" },
    { value: "French Guiana", abbrev: "GF", label: "French Guiana" },
    { value: "French Polynesia", abbrev: "PF", label: "French Polynesia" },
    { value: "French Southern Territories", abbrev: "TF", label: "French Southern Territories" },
    { value: "Gabon", abbrev: "GA", label: "Gabon" },
    { value: "Gambia", abbrev: "GM", label: "Gambia" },
    { value: "Georgia", abbrev: "GE", label: "Georgia" },
    { value: "Germany", abbrev: "DE", label: "Germany" },
    { value: "Ghana", abbrev: "GH", label: "Ghana" },
    { value: "Gibraltar", abbrev: "GI", label: "Gibraltar" },
    { value: "Greece", abbrev: "GR", label: "Greece" },
    { value: "Greenland", abbrev: "GL", label: "Greenland" },
    { value: "Grenada", abbrev: "GD", label: "Grenada" },
    { value: "Guadeloupe", abbrev: "GP", label: "Guadeloupe" },
    { value: "Guam", abbrev: "GU", label: "Guam" },
    { value: "Guatemala", abbrev: "GT", label: "Guatemala" },
    { value: "Guernsey", abbrev: "GG", label: "Guernsey" },
    { value: "Guinea", abbrev: "GN", label: "Guinea" },
    { value: "Guinea-Bissau", abbrev: "GW", label: "Guinea-Bissau" },
    { value: "Guyana", abbrev: "GY", label: "Guyana" },
    { value: "Haiti", abbrev: "HT", label: "Haiti" },
    { value: "Heard Island and Mcdonald Islands", abbrev: "HM", label: "Heard Island and Mcdonald Islands" },
    { value: "Holy See (Vatican City State)", abbrev: "VA", label: "Holy See (Vatican City State)" },
    { value: "Honduras", abbrev: "HN", label: "Honduras" },
    { value: "Hong Kong", abbrev: "HK", label: "Hong Kong" },
    { value: "Hungary", abbrev: "HU", label: "Hungary" },
    { value: "Iceland", abbrev: "IS", label: "Iceland" },
    { value: "India", abbrev: "IN", label: "India" },
    { value: "Indonesia", abbrev: "ID", label: "Indonesia" },
    { value: "Iran, Islamic Republic Of", abbrev: "IR", label: "Iran, Islamic Republic Of" },
    { value: "Iraq", abbrev: "IQ", label: "Iraq" },
    { value: "Ireland", abbrev: "IE", label: "Ireland" },
    { value: "Isle of Man", abbrev: "IM", label: "Isle of Man" },
    { value: "Israel", abbrev: "IL", label: "Israel" },
    { value: "Italy", abbrev: "IT", label: "Italy" },
    { value: "Jamaica", abbrev: "JM", label: "Jamaica" },
    { value: "Japan", abbrev: "JP", label: "Japan" },
    { value: "Jersey", abbrev: "JE", label: "Jersey" },
    { value: "Jordan", abbrev: "JO", label: "Jordan" },
    { value: "Kazakhstan", abbrev: "KZ", label: "Kazakhstan" },
    { value: "Kenya", abbrev: "KE", label: "Kenya" },
    { value: "Kiribati", abbrev: "KI", label: "Kiribati" },
    { value: "Korea, Democratic People'S Republic of", abbrev: "KP", label: "Korea, Democratic People'S Republic of" },
    { value: "Korea, Republic of", abbrev: "KR", label: "Korea, Republic of" },
    { value: "Kuwait", abbrev: "KW", label: "Kuwait" },
    { value: "Kyrgyzstan", abbrev: "KG", label: "Kyrgyzstan" },
    { value: "Lao People'S Democratic Republic", abbrev: "LA", label: "Lao People'S Democratic Republic" },
    { value: "Latvia", abbrev: "LV", label: "Latvia" },
    { value: "Lebanon", abbrev: "LB", label: "Lebanon" },
    { value: "Lesotho", abbrev: "LS", label: "Lesotho" },
    { value: "Liberia", abbrev: "LR", label: "Liberia" },
    { value: "Libyan Arab Jamahiriya", abbrev: "LY", label: "Libyan Arab Jamahiriya" },
    { value: "Liechtenstein", abbrev: "LI", label: "Liechtenstein" },
    { value: "Lithuania", abbrev: "LT", label: "Lithuania" },
    { value: "Luxembourg", abbrev: "LU", label: "Luxembourg" },
    { value: "Macao", abbrev: "MO", label: "Macao" },
    { value: "Macedonia, The Former Yugoslav Republic of", abbrev: "MK", label: "Macedonia, The Former Yugoslav Republic of" },
    { value: "Madagascar", abbrev: "MG", label: "Madagascar" },
    { value: "Malawi", abbrev: "MW", label: "Malawi" },
    { value: "Malaysia", abbrev: "MY", label: "Malaysia" },
    { value: "Maldives", abbrev: "MV", label: "Maldives" },
    { value: "Mali", abbrev: "ML", label: "Mali" },
    { value: "Malta", abbrev: "MT", label: "Malta" },
    { value: "Marshall Islands", abbrev: "MH", label: "Marshall Islands" },
    { value: "Martinique", abbrev: "MQ", label: "Martinique" },
    { value: "Mauritania", abbrev: "MR", label: "Mauritania" },
    { value: "Mauritius", abbrev: "MU", label: "Mauritius" },
    { value: "Mayotte", abbrev: "YT", label: "Mayotte" },
    { value: "Mexico", abbrev: "MX", label: "Mexico" },
    { value: "Micronesia, Federated States of", abbrev: "FM", label: "Micronesia, Federated States of" },
    { value: "Moldova, Republic of", abbrev: "MD", label: "Moldova, Republic of" },
    { value: "Monaco", abbrev: "MC", label: "Monaco" },
    { value: "Mongolia", abbrev: "MN", label: "Mongolia" },
    { value: "Montserrat", abbrev: "MS", label: "Montserrat" },
    { value: "Morocco", abbrev: "MA", label: "Morocco" },
    { value: "Mozambique", abbrev: "MZ", label: "Mozambique" },
    { value: "Myanmar", abbrev: "MM", label: "Myanmar" },
    { value: "Namibia", abbrev: "NA", label: "Namibia" },
    { value: "Nauru", abbrev: "NR", label: "Nauru" },
    { value: "Nepal", abbrev: "NP", label: "Nepal" },
    { value: "Netherlands", abbrev: "NL", label: "Netherlands" },
    { value: "Netherlands Antilles", abbrev: "AN", label: "Netherlands Antilles" },
    { value: "New Caledonia", abbrev: "NC", label: "New Caledonia" },
    { value: "New Zealand", abbrev: "NZ", label: "New Zealand" },
    { value: "Nicaragua", abbrev: "NI", label: "Nicaragua" },
    { value: "Niger", abbrev: "NE", label: "Niger" },
    { value: "Nigeria", abbrev: "NG", label: "Nigeria" },
    { value: "Niue", abbrev: "NU", label: "Niue" },
    { value: "Norfolk Island", abbrev: "NF", label: "Norfolk Island" },
    { value: "Northern Mariana Islands", abbrev: "MP", label: "Northern Mariana Islands" },
    { value: "Norway", abbrev: "NO", label: "Norway" },
    { value: "Oman", abbrev: "OM", label: "Oman" },
    { value: "Pakistan", abbrev: "PK", label: "Pakistan" },
    { value: "Palau", abbrev: "PW", label: "Palau" },
    { value: "Palestinian Territory, Occupied", abbrev: "PS", label: "Palestinian Territory, Occupied" },
    { value: "Panama", abbrev: "PA", label: "Panama" },
    { value: "Papua New Guinea", abbrev: "PG", label: "Papua New Guinea" },
    { value: "Paraguay", abbrev: "PY", label: "Paraguay" },
    { value: "Peru", abbrev: "PE", label: "Peru" },
    { value: "Philippines", abbrev: "PH", label: "Philippines" },
    { value: "Pitcairn", abbrev: "PN", label: "Pitcairn" },
    { value: "Poland", abbrev: "PL", label: "Poland" },
    { value: "Portugal", abbrev: "PT", label: "Portugal" },
    { value: "Puerto Rico", abbrev: "PR", label: "Puerto Rico" },
    { value: "Qatar", abbrev: "QA", label: "Qatar" },
    { value: "Reunion", abbrev: "RE", label: "Reunion" },
    { value: "Romania", abbrev: "RO", label: "Romania" },
    { value: "Russian Federation", abbrev: "RU", label: "Russian Federation" },
    { value: "RWANDA", abbrev: "RW", label: "RWANDA" },
    { value: "Saint Helena", abbrev: "SH", label: "Saint Helena" },
    { value: "Saint Kitts and Nevis", abbrev: "KN", label: "Saint Kitts and Nevis" },
    { value: "Saint Lucia", abbrev: "LC", label: "Saint Lucia" },
    { value: "Saint Pierre and Miquelon", abbrev: "PM", label: "Saint Pierre and Miquelon" },
    { value: "Saint Vincent and the Grenadines", abbrev: "VC", label: "Saint Vincent and the Grenadines" },
    { value: "Samoa", abbrev: "WS", label: "Samoa" },
    { value: "San Marino", abbrev: "SM", label: "San Marino" },
    { value: "Sao Tome and Principe", abbrev: "ST", label: "Sao Tome and Principe" },
    { value: "Saudi Arabia", abbrev: "SA", label: "Saudi Arabia" },
    { value: "Senegal", abbrev: "SN", label: "Senegal" },
    { value: "Serbia and Montenegro", abbrev: "CS", label: "Serbia and Montenegro" },
    { value: "Seychelles", abbrev: "SC", label: "Seychelles" },
    { value: "Sierra Leone", abbrev: "SL", label: "Sierra Leone" },
    { value: "Singapore", abbrev: "SG", label: "Singapore" },
    { value: "Slovakia", abbrev: "SK", label: "Slovakia" },
    { value: "Slovenia", abbrev: "SI", label: "Slovenia" },
    { value: "Solomon Islands", abbrev: "SB", label: "Solomon Islands" },
    { value: "Somalia", abbrev: "SO", label: "Somalia" },
    { value: "South Africa", abbrev: "ZA", label: "South Africa" },
    { value: "South Georgia and the South Sandwich Islands", abbrev: "GS", label: "South Georgia and the South Sandwich Islands" },
    { value: "Spain", abbrev: "ES", label: "Spain" },
    { value: "Sri Lanka", abbrev: "LK", label: "Sri Lanka" },
    { value: "Sudan", abbrev: "SD", label: "Sudan" },
    { value: "Suriname", abbrev: "SR", label: "Suriname" },
    { value: "Svalbard and Jan Mayen", abbrev: "SJ", label: "Svalbard and Jan Mayen" },
    { value: "Swaziland", abbrev: "SZ", label: "Swaziland" },
    { value: "Sweden", abbrev: "SE", label: "Sweden" },
    { value: "Switzerland", abbrev: "CH", label: "Switzerland" },
    { value: "Syrian Arab Republic", abbrev: "SY", label: "Syrian Arab Republic" },
    { value: "Taiwan, Province of China", abbrev: "TW", label: "Taiwan, Province of China" },
    { value: "Tajikistan", abbrev: "TJ", label: "Tajikistan" },
    { value: "Tanzania, United Republic of", abbrev: "TZ", label: "Tanzania, United Republic of" },
    { value: "Thailand", abbrev: "TH", label: "Thailand" },
    { value: "Timor-Leste", abbrev: "TL", label: "Timor-Leste" },
    { value: "Togo", abbrev: "TG", label: "Togo" },
    { value: "Tokelau", abbrev: "TK", label: "Tokelau" },
    { value: "Tonga", abbrev: "TO", label: "Tonga" },
    { value: "Trinidad and Tobago", abbrev: "TT", label: "Trinidad and Tobago" },
    { value: "Tunisia", abbrev: "TN", label: "Tunisia" },
    { value: "Turkey", abbrev: "TR", label: "Turkey" },
    { value: "Turkmenistan", abbrev: "TM", label: "Turkmenistan" },
    { value: "Turks and Caicos Islands", abbrev: "TC", label: "Turks and Caicos Islands" },
    { value: "Tuvalu", abbrev: "TV", label: "Tuvalu" },
    { value: "Uganda", abbrev: "UG", label: "Uganda" },
    { value: "Ukraine", abbrev: "UA", label: "Ukraine" },
    { value: "United Arab Emirates", abbrev: "AE", label: "United Arab Emirates" },
    { value: "United Kingdom", abbrev: "GB", label: "United Kingdom" },
    { value: "United States", abbrev: "US", label: "United States" },
    { value: "United States Minor Outlying Islands", abbrev: "UM", label: "United States Minor Outlying Islands" },
    { value: "Uruguay", abbrev: "UY", label: "Uruguay" },
    { value: "Uzbekistan", abbrev: "UZ", label: "Uzbekistan" },
    { value: "Vanuatu", abbrev: "VU", label: "Vanuatu" },
    { value: "Venezuela", abbrev: "VE", label: "Venezuela" },
    { value: "Viet Nam", abbrev: "VN", label: "Viet Nam" },
    { value: "Virgin Islands, British", abbrev: "VG", label: "Virgin Islands, British" },
    { value: "Virgin Islands, U.S.", abbrev: "VI", label: "Virgin Islands, U.S." },
    { value: "Wallis and Futuna", abbrev: "WF", label: "Wallis and Futuna" },
    { value: "Western Sahara", abbrev: "EH", label: "Western Sahara" },
    { value: "Yemen", abbrev: "YE", label: "Yemen" },
    { value: "Zambia", abbrev: "ZM", label: "Zambia" },
    { value: "Zimbabwe", abbrev: "ZW", label: "Zimbabwe" }
];
